### ISSUE TITLE
执行schema.sql中的sql语句报错：[HY000][1293] Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

### ISSUE THREAD

**Issue by NoGameNoLife00** [EveryoneJavaBlog/everyone-java-blog#52]
在执行schema.sql中的创建表语句
```
CREATE TABLE `java_blog`.`blog_config` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `web_user_id` INT NOT NULL COMMENT '用户ID',
  `introduction` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '用户简介',
  `address` VARCHAR(100) NOT NULL COMMENT '用户博客地址',
  PRIMARY KEY (`id`)
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='WEB端用户博客配置表';
```

会报错：`[HY000][1293] Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause`

**Comment by NoGameNoLife00** [comment]
网上查到的原因是：给一个timestamp设置为on update current_timestamp的时候，其他的timestamp字段需要显式设定default值，但是一个表中有两个timestamp字段的时候，需要把第一个字段设置为current_timestamp，第二个字段不设置默认值才能成功创建表

也就是要改成这样才能成功创建表：
`CREATE TABLE `java_blog`.`blog_config` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_time` TIMESTAMP NOT NULL COMMENT '创建时间',
  `web_user_id` INT NOT NULL COMMENT '用户ID',
  `introduction` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '用户简介',
  `address` VARCHAR(100) NOT NULL COMMENT '用户博客地址',
  PRIMARY KEY (`id`)
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='WEB端用户博客配置表';
`
还有其他什么解决方法吗？

**Comment by xiaolongzuo** [comment]
怎么感觉你说的有点自相矛盾。。。。

**Comment by NoGameNoLife00** [comment]
@xiaolongzuo  这个是网上的解释，链接：http://www.cnblogs.com/yoyo24456/p/3632462.html
其实我就是想单纯问下为什么直接执行schema.sql文件会报这个错误。。

**Comment by xiaolongzuo** [comment]
这个按说不会的。你是mysql吗。

**Comment by xiaolongzuo** [comment]
还有就是你的版本是多少。

**Comment by NoGameNoLife00** [comment]
@xiaolongzuo mysql 5.0

**Comment by NoGameNoLife00** [comment]
@xiaolongzuo 我试了下另外一台机子mysql 5.6上去执行，可以成功。应该是版本问题5.0不支持这个语法吧
